- name: prepare reproducer script
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/oc-get-loop.sh"
    mode: 0755
    content: |
      #!/bin/bash
      set -x

      eval $(${HOME}/ci-framework-data/bin/crc oc-env)
      export KUBECONFIG="${HOME}/.crc/machines/crc/kubeconfig"

      while true; do
        ons_clouds_yaml=""
        ons_secret=""
        tempest_secret=""
        tempest_endpoint=""

        ons_clouds_yaml=$(oc get configmap -n openstack openstack-config -o 'jsonpath={.data.clouds\.yaml}')
        ons_secret=$(oc get secret -n openstack openstack-config-secret -o 'jsonpath={.data.secure\.yaml}')

        KEYSCT=$(oc get keystoneapi keystone -o json | jq -r .spec.secret)
        KEYSEL=$(oc get keystoneapi keystone -o json |jq -r .spec.passwordSelectors.admin)
        if [[ -n "$KEYSCT" && -n "$KEYSEL" ]]; then
          tempest_secret=$(oc get secret "$KEYSCT" -o json | jq -r .data."${KEYSEL}" | base64 -d)
        fi

        tempest_endpoint=$(oc get keystoneapi keystone -o json | jq -r .status.apiEndpoint.public)

        if [[ -z "$ons_clouds_yaml" || -z "$ons_secret" || -z "$tempest_secret" || -z "$tempest_endpoint" ]]; then
          echo "ERROR: something is missing"
        fi
      done

- name: start repeated oc get
  ansible.builtin.shell:
    cmd:
      tmux new-session -A -s debugoc -d;
      tmux send -t debugoc "timeout 24h {{ ansible_user_dir }}/oc-get-loop.sh |& tee /tmp/oc-get-loop.log" ENTER;
